<?php
/**
 * BookingInput
 *
 * PHP version 5
 *
 * @category Class
 * @package  Listae\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * listae API 2.0
 *
 * Documentación de los servicios REST de listae
 *
 * OpenAPI spec version: 2.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Listae\Client\Model;

use \ArrayAccess;
use \Listae\Client\ObjectSerializer;

/**
 * BookingInput Class Doc Comment
 *
 * @category Class
 * @package  Listae\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookingInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BookingInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'booking_date' => 'string',
'booking_time' => 'string',
'bookers' => 'int',
'coupon_code' => 'string',
'name' => 'string',
'email' => 'string',
'suscribe' => 'bool',
'reminder' => 'bool',
'comment' => 'string',
'menu' => 'string',
'dining_area' => 'string',
'phone' => '\Listae\Client\Model\PhoneInput'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'booking_date' => null,
'booking_time' => null,
'bookers' => 'int32',
'coupon_code' => null,
'name' => null,
'email' => null,
'suscribe' => null,
'reminder' => null,
'comment' => null,
'menu' => null,
'dining_area' => null,
'phone' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'booking_date' => 'bookingDate',
'booking_time' => 'bookingTime',
'bookers' => 'bookers',
'coupon_code' => 'couponCode',
'name' => 'name',
'email' => 'email',
'suscribe' => 'suscribe',
'reminder' => 'reminder',
'comment' => 'comment',
'menu' => 'menu',
'dining_area' => 'diningArea',
'phone' => 'phone'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'booking_date' => 'setBookingDate',
'booking_time' => 'setBookingTime',
'bookers' => 'setBookers',
'coupon_code' => 'setCouponCode',
'name' => 'setName',
'email' => 'setEmail',
'suscribe' => 'setSuscribe',
'reminder' => 'setReminder',
'comment' => 'setComment',
'menu' => 'setMenu',
'dining_area' => 'setDiningArea',
'phone' => 'setPhone'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'booking_date' => 'getBookingDate',
'booking_time' => 'getBookingTime',
'bookers' => 'getBookers',
'coupon_code' => 'getCouponCode',
'name' => 'getName',
'email' => 'getEmail',
'suscribe' => 'getSuscribe',
'reminder' => 'getReminder',
'comment' => 'getComment',
'menu' => 'getMenu',
'dining_area' => 'getDiningArea',
'phone' => 'getPhone'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['booking_date'] = isset($data['booking_date']) ? $data['booking_date'] : null;
        $this->container['booking_time'] = isset($data['booking_time']) ? $data['booking_time'] : null;
        $this->container['bookers'] = isset($data['bookers']) ? $data['bookers'] : null;
        $this->container['coupon_code'] = isset($data['coupon_code']) ? $data['coupon_code'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['suscribe'] = isset($data['suscribe']) ? $data['suscribe'] : null;
        $this->container['reminder'] = isset($data['reminder']) ? $data['reminder'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['menu'] = isset($data['menu']) ? $data['menu'] : null;
        $this->container['dining_area'] = isset($data['dining_area']) ? $data['dining_area'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets booking_date
     *
     * @return string
     */
    public function getBookingDate()
    {
        return $this->container['booking_date'];
    }

    /**
     * Sets booking_date
     *
     * @param string $booking_date Fecha de la reserva
     *
     * @return $this
     */
    public function setBookingDate($booking_date)
    {
        $this->container['booking_date'] = $booking_date;

        return $this;
    }

    /**
     * Gets booking_time
     *
     * @return string
     */
    public function getBookingTime()
    {
        return $this->container['booking_time'];
    }

    /**
     * Sets booking_time
     *
     * @param string $booking_time Hora de la reserva
     *
     * @return $this
     */
    public function setBookingTime($booking_time)
    {
        $this->container['booking_time'] = $booking_time;

        return $this;
    }

    /**
     * Gets bookers
     *
     * @return int
     */
    public function getBookers()
    {
        return $this->container['bookers'];
    }

    /**
     * Sets bookers
     *
     * @param int $bookers Número de comensales
     *
     * @return $this
     */
    public function setBookers($bookers)
    {
        $this->container['bookers'] = $bookers;

        return $this;
    }

    /**
     * Gets coupon_code
     *
     * @return string
     */
    public function getCouponCode()
    {
        return $this->container['coupon_code'];
    }

    /**
     * Sets coupon_code
     *
     * @param string $coupon_code Hora de la reserva
     *
     * @return $this
     */
    public function setCouponCode($coupon_code)
    {
        $this->container['coupon_code'] = $coupon_code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Nombre de contacto del usuario de la reserva
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Email de contacto del usuario de la reserva
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets suscribe
     *
     * @return bool
     */
    public function getSuscribe()
    {
        return $this->container['suscribe'];
    }

    /**
     * Sets suscribe
     *
     * @param bool $suscribe Si se suscribe a novedades del restaurante (o se afilia al club vip del mismo)
     *
     * @return $this
     */
    public function setSuscribe($suscribe)
    {
        $this->container['suscribe'] = $suscribe;

        return $this;
    }

    /**
     * Gets reminder
     *
     * @return bool
     */
    public function getReminder()
    {
        return $this->container['reminder'];
    }

    /**
     * Sets reminder
     *
     * @param bool $reminder Indica si se le va a enviar por email un recordatorio de la reserva minutos antes de la misma (por defecto sí)
     *
     * @return $this
     */
    public function setReminder($reminder)
    {
        $this->container['reminder'] = $reminder;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string $comment Comentarios y observaciones en la reserva por parte del usuario de la misma
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets menu
     *
     * @return string
     */
    public function getMenu()
    {
        return $this->container['menu'];
    }

    /**
     * Sets menu
     *
     * @param string $menu Identificador del menú seleccionado para la reserva
     *
     * @return $this
     */
    public function setMenu($menu)
    {
        $this->container['menu'] = $menu;

        return $this;
    }

    /**
     * Gets dining_area
     *
     * @return string
     */
    public function getDiningArea()
    {
        return $this->container['dining_area'];
    }

    /**
     * Sets dining_area
     *
     * @param string $dining_area Identificador de la zona/sala seleccionada para la reserva
     *
     * @return $this
     */
    public function setDiningArea($dining_area)
    {
        $this->container['dining_area'] = $dining_area;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return \Listae\Client\Model\PhoneInput
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param \Listae\Client\Model\PhoneInput $phone phone
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
